networks:
  frontend:
    ipam:
    config:
      - subnet: $FRONTEND_SUBNET
        gateway: $FRONTEND
  backend:
    ipam:
    config:
      - subnet: $BACKEND_SUBNET
        gateway: $BACKEND

include:
  - service-adguard.yaml
  - service-adguard-sync.yaml
  - service-asf.yaml
  - service-authelia.yaml
  - service-bitwarden.yaml
  - service-cloudflared.yaml
  - service-deluge.yaml
  - service-flame.yaml
  - service-freshrss.yaml
  - service-gluetun.yaml
  - service-home-assistant.yaml
  - service-mongo.yaml
  - service-mosquitto.yaml
  - service-pairdrop.yaml
  - service-portainer.yaml
  - service-postgres.yaml
  - service-socket-proxy.yaml
  - service-tautulli.yaml
  - service-traefik.yaml
  - service-unifi.yaml
  - service-uptime-kuma.yaml
  - service-watchtower.yaml
  - service-zipline.yaml
