networks:
  frontend:
    name: frontend
    ipam:
      config:
        - subnet: $FRONTEND_SUBNET
          gateway: $FRONTEND
  backend:
    name: backend
    ipam:
      config:
        - subnet: $BACKEND_SUBNET
          gateway: $BACKEND

include:
  - service-adguard.yaml
  - service-adguard-sync.yaml
  - service-asf.yaml
  - service-authelia.yaml            # Required
  - service-bitwarden.yaml
  - service-deluge.yaml
  - service-esphome.yaml
  - service-flame.yaml
  - service-freshrss.yaml
  - service-gluetun.yaml
  - service-home-assistant.yaml
  - service-mongo.yaml
  - service-mosquitto.yaml
  - service-netbootxyz.yaml
  - service-pairdrop.yaml
  - service-portainer.yaml
  - service-portainer-agent.yaml
  - service-postgres.yaml            # Required
  - service-ryot.yaml
  - service-socket-proxy.yaml        # Required
  - service-tautulli.yaml
  - service-traefik.yaml             # Required
  - service-unifi.yaml
  - service-uptime-kuma.yaml
  - service-watchtower.yaml
  - service-wyoming-openwakeword.yaml
  - service-wyoming-piper.yaml
  - service-wyoming-whisper.yaml
  - service-zipline.yaml
