services:
  adguard:
    container_name: adguard
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    expose:
      - 80
    image: adguard/adguardhome:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`dns.$DOMAIN`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.http.services.adguard.loadbalancer.server.url=http://$DOCKER_IP
    networks:
      - frontend
    ports:
      - 53:53
      - 53:53/udp
#     - 3000:3000
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $DOCKER/adguard/conf:/opt/adguardhome/conf
      - $DOCKER/adguard/work:/opt/adguardhome/work
