services:
  flame:
    container_name: flame
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=$FLAME_PASSWORD
    image: pawelmalak/flame:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame.rule=Host(`start.$DOMAIN`)
      - traefik.http.services.flame.loadbalancer.server.port=5005
    networks:
      - frontend
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $DOCKER/flame:/app/data
