services:
  freshrss:
    container_name: freshrss
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: linuxserver/freshrss:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`rss.$DOMAIN`)
      - traefik.http.services.freshrss.loadbalancer.server.port=80
    networks:
      - frontend
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $DOCKER/freshrss:/config
