services:
  nginx:
    container_name: nginx
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: ghcr.io/linuxserver/nginx:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`$WEB`) || Host(`subdomain.$WEB`)
      - traefik.http.services.nginx.loadbalancer.server.port=80
    networks:
      - frontend
    restart: unless-stopped
    volumes:
      - $DOCKER/nginx:/config
