services:
  pairdrop:
    container_name: pairdrop
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - RATE_LIMIT=true
      - WS_FALLBACK=true
    image: linuxserver/pairdrop:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.pairdrop.rule=Host(`file.$WEB`)
      - traefik.http.services.pairdrop.loadbalancer.server.port=3000
    networks:
      - frontend
    restart: unless-stopped
