services:
  tautulli:
    container_name: tautulli
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: linuxserver/tautulli:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.$DOMAIN`)
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    networks:
      - frontend
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $DOCKER/tautulli:/config
