services:
  mosquitto:
    container_name: mosquitto
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: eclipse-mosquitto:latest
    networks:
      - frontend
    ports:
      - 1884:1884
    restart: unless-stopped
    volumes:
      - $DOCKER/mosquitto/config:/mosquitto/config
      - $DOCKER/mosquitto/data:/mosquitto/data
      - $DOCKER/mosquitto/log:/mosquitto/log
