services:
  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      - authelia
      - socket-proxy
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: louislam/uptime-kuma:2-slim
    network_mode: host
    restart: unless-stopped
    volumes:
      - $DOCKER/uptime-kuma:/app/data
