services:
  home-assistant:
    container_name: home-assistant
    depends_on:
      - authelia
      - postgres
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: ghcr.io/linuxserver/homeassistant:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - $DOCKER/home-assistant:/config
