services:
  wyoming-piper:
    container_name: wyoming-piper
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PIPER_VOICE=en_US-ryan-medium
    image: ghcr.io/linuxserver/piper:latest
    networks:
      - frontend
    ports:
      - 127.0.0.1:10200:10200
    restart: unless-stopped
    volumes:
      - $DATA/wyoming-piper:/config
