services:
  traefik:
    container_name: traefik
    depends_on:
      - socket-proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - CF_DNS_API_TOKEN=$CLOUDFLARE_API
      - CF_ZONE_API_TOKEN=$CLOUDFLARE_API
    image: traefik:v3.4
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.$WEB`)
      - traefik.http.routers.traefik.service=api@internal
    networks:
      - backend
      - frontend
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - $DOCKER/traefik/acme.json:/acme.json
      - $DOCKER/traefik/configuration.yml:/configuration.yml
      - $DOCKER/traefik/traefik.log:/traefik.log
      - $DOCKER/traefik/traefik.yml:/traefik.yml
