services:
  adguard:
    container_name: adguard
    depends_on:
      - authelia
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: adguard/adguardhome:latest
    networks:
      - frontend
    ports:
      - 53:53
      - 53:53/udp
      - 80:80
#     - 3000:3000
    restart: unless-stopped
    volumes:
      - $DOCKER/adguard/conf:/opt/adguardhome/conf
      - $DOCKER/adguard/work:/opt/adguardhome/work
