services:
  watchtower:
    container_name: watchtower
    depends_on:
      - socket-proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WATCHTOWER_CLEANUP=true
      - DOCKER_HOST=tcp://socket-proxy:2375
      - WATCHTOWER_SCHEDULE=0 0 3 * * 5
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=$EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=$EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=$EMAIL_HOST
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=$EMAIL_PORT
    image: containrrr/watchtower:latest
    networks:
      - backend
    restart: unless-stopped
    user: $PUID:$PGID
