services:
  deluge:
    container_name: deluge
    depends_on:
      - gluetun
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DELUGE_LOGLEVEL=warning
    image: ghcr.io/linuxserver/deluge:latest
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - $DOCKER/deluge:/config
      - $DATA/deluge:/downloads
