services:
  adguard-sync:
    container_name: adguard-sync
    depends_on:
      - adguard
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: linuxserver/adguardhome-sync:latest
    networks:
      - frontend
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - $DOCKER/adguard-sync:/config
