services:
  unifi:
    container_name: unifi
    depends_on:
      - authelia
      - mongo
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MONGO_USER=$MONGO_USER_UNIFI
      - MONGO_PASS=$MONGO_PASS_UNIFI
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    image: linuxserver/unifi-network-application:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.unifi.rule=Host(`unifi.$WEB`)
      - traefik.http.services.unifi.loadbalancer.server.port=8443
      - traefik.http.services.unifi.loadbalancer.server.scheme=https
    networks:
      - backend
      - frontend
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
    volumes:
      - $DOCKER/unifi:/config
