services:
  portainer-agent:
    container_name: portainer-agent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: portainer/agent:latest
    networks:
      - frontend
    ports:
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
