default_2fa_method: mobile_push
theme: auto

access_control:
  default_policy: deny
  rules:
  - domain:
    - xxx.example.com
    policy: bypass
  - domain: "*.example.com"
    policy: bypass
    networks: x.x.x.x
  - domain: "*.example.com"
    policy: two_factor

authentication_backend:
  file:
    path: /config/users.yml
    search:
      email: true

duo_api:
  hostname: xxx
  integration_key: xxx
  secret_key: xxx

identity_validation:
  reset_password:
    jwt_secret: xxx

log:
  level: warn
  file_path: /config/authelia.log
  keep_stdout: true

notifier:
  smtp:
    address: smtp://xxx:25
    sender: "xxx"
    subject: "{title}"
    startup_check_address: xxx

password_policy:
  standard:
    enabled: true
    min_length: 20
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

regulation:
  max_retries: 3
  find_time: '5 minutes'
  ban_time: '1 hour'

server:
  buffers:
    read: 8192
    write: 8192

session:
  secret: xxx
  cookies:
    - domain: example.com
      authelia_url: 'https://login.example.com'
      default_redirection_url: 'https://start.example.com'
      remember_me: -1

storage:
  encryption_key: xxx
  postgres:
    address: tcp://postgres:5432
    database: authelia
    username: authelia
    password: xxx

totp:
  issuer: example.com

webauthn:
  disable: true
