default_2fa_method: mobile_push
theme: auto

authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: argon2
    search:
      email: true

duo_api:
  hostname: xxx
  integration_key: xxx
  secret_key: xxx

totp:
  issuer: example.com

webauthn:
  disable: true

access_control:
  default_policy: deny
  rules:
  - domain:
    - xxx.example.com
    policy: bypass
  - domain: "*.example.com"
    networks: x.x.x.x
    policy: bypass
  - domain: "*.example.com"
    policy: two_factor

password_policy:
  standard:
    enabled: true
    min_length: 16
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

session:
  secret: xxx
  cookies:
    - domain: example.com
      authelia_url: 'https://login.example.com'
      default_redirection_url: 'https://start.example.com'
      remember_me: -1

storage:
  encryption_key: xxx
  postgres:
    address: tcp://postgres:5432
    database: authelia
    username: authelia
    password: xxx

notifier:
  disable_startup_check: true
  smtp:
    address: smtp://xxx:25
    sender: "xxx"
    subject: "{title}"
    startup_check_address: xxx

ntp:
  address: "time.cloudflare.com:123"
  version: 4

log:
  file_path: /config/authelia.log
  keep_stdout: true
  level: warn

identity_validation:
  reset_password:
    jwt_secret: xxx
