http:
  middlewares:
    default:
      chain:
        middlewares:
          - forwardauth
          - headers
          - ratelimit
    forwardauth:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth"
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
        trustForwardHeader: true
    headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          Server: ""
          X-Robots-Tag: "none, noarchive, nosnippet, notranslate, noimageindex"
        forceSTSHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        permissionsPolicy: "autoplay=(), camera=(), display-capture=(), fullscreen=(), geolocation=(), microphone=(), web-share=()"
        referrerPolicy: "same-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
    ratelimit:
      rateLimit:
        average: 100
        burst: 50

tls:
  certificates:
    - certFile: /certificates/example.com.cert
      keyFile: /certificates/example.com.key
  options:
    secure:
      minVersion: VersionTLS13
      sniStrict: true
