http:
  middlewares:
    default:
      chain:
        middlewares:
          - forwardauth
          - headers
          - ratelimit
    forwardauth:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth"
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
        trustForwardHeader: true
    headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          Server: ""
          X-Robots-Tag: "none, nosnippet, notranslate, noimageindex"
        forceSTSHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        permissionsPolicy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
        referrerPolicy: "same-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
    ratelimit:
      rateLimit:
        average: 100
        burst: 50
  routers:
    adguard:
      rule: "Host (`dns.example.com`)"
      service: adguard
    esphome:
      rule: "Host (`esphome.example.com`)"
      service: esphome
    home-assistant:
      rule: "Host (`home.example.com`)"
      service: home-assistant
    uptime-kuma:
      rule: "Host (`status.example.com`)"
      service: uptime-kuma
  services:
    adguard:
      loadBalancer:
        servers:
          - url: http://x.x.x.x
    esphome:
      loadBalancer:
        servers:
          - url: http://x.x.x.x:6052
    home-assistant:
      loadBalancer:
        servers:
          - url: http://x.x.x.x:8123
    uptime-kuma:
      loadBalancer:
        servers:
          - url: http://x.x.x.x:3001

tls:
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
