default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

group:
  ignored_unavailable_entities:
    entities:
      - stt.whisper

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - x.x.x.x/24
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 108.162.192.0/18
    - 131.0.72.0/22
    - 141.101.64.0/18
    - 162.158.0.0/15
    - 172.64.0.0/13
    - 173.245.48.0/20
    - 188.114.96.0/20
    - 190.93.240.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17

recorder:
  db_url: postgresql://xxx:xxx@xxx/xxx

template:
  - sensor:
    - name: "Unavailable Entities"
      unique_id: unavailable_entities
      icon: "{{ iif(states(this.entity_id)|int(-1) > 0, 'mdi:alert-circle', 'mdi:check-circle') }}"
      state_class: measurement
      unit_of_measurement: entities
      state: >
        {% set entities = state_attr(this.entity_id, 'entity_id') %}
        {{ entities | count if entities != none else none }}
      attributes:
        entity_id: >
          {% set ignore_seconds = 60 %}
          {% set ignored = state_attr('group.ignored_unavailable_entities', 'entity_id') %}
          {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {% set entities = states
              | rejectattr('domain','in',['button', 'event', 'group', 'image', 'input_button', 'input_text', 'remote', 'tts', 'scene', 'stt'])
              | rejectattr('last_changed', 'ge', ignore_ts) %}
          {% set entities =  entities | rejectattr('entity_id', 'in', ignored) if ignored != none else entities %}
          {{ entities | map(attribute='entity_id') | reject('has_value') | list | sort }}
