services:
  wyoming-whisper:
    container_name: wyoming-whisper
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WHISPER_MODEL=base-int8
      - WHISPER_BEAM=1
      - WHISPER_LANG=en
    image: ghcr.io/linuxserver/faster-whisper:latest
    networks:
      - frontend
    ports:
      - 10300:10300
    restart: unless-stopped
    volumes:
      - $DATA/wyoming-whisper:/config
