services:
  mongo:
    container_name: mongo
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    image: mongo:7.0
    networks:
      - backend
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - $DOCKER/mongo/configdb:/data/configdb
      - $DOCKER/mongo/db:/data/db
      - $DOCKER/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
