services:
  zipline:
    container_name: zipline
    depends_on:
      - authelia
      - postgres
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - CORE_DATABASE_URL=$ZIPLINE_DB
      - CORE_SECRET=$ZIPLINE_SECRET
      - FEATURES_ROBOTS_TXT=true
      - MFA_TOTP_ISSUER=$ZIPLINE_NAME
      - UPLOADER_ROUTE=/f
      - UPLOADER_ADMIN_LIMIT=100mb
      - UPLOADER_USER_LIMIT=100mb
      - UPLOADER_DEFAULT_EXPIRATION=1w
      - URLS_ROUTE=/u
      - WEBSITE_TITLE=$ZIPLINE_NAME
    image: ghcr.io/diced/zipline:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.zipline.rule=Host(`share.$WEB`)
      - traefik.http.services.zipline.loadbalancer.server.port=3000
    networks:
      - backend
      - frontend
    restart: unless-stopped
    volumes:
      - $DOCKER/zipline:/zipline/public
      - $DATA/zipline:/zipline/uploads
