services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER/mediaserver/jackett/data:/data
      - $DOCKER/mediaserver/jackett/config:/config
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: container:gluetun
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.$WEB`)
      - traefik.http.services.jackett.loadbalancer.server.port=9117